name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  # cant make e2e working on github, seems some timing issues? locally they work ok
#  e2e-tests:
#    name: E2E Tests
#    runs-on: ubuntu-latest
#    env:
#      PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
#      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
#      E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
#      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
#      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
#      ENV_NAME: tests
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 18
#          cache: "npm"
#      - name: Install dependencies
#        run: npm ci
#      - name: Install Playwright browsers
#        run: npx playwright install --with-deps chromium
#      - name: Run Playwright tests
#        run: npm run test:e2e
#      - name: Upload Playwright report
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30
